# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

for:
-
  skip_tags: true

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

before_deploy:
  - ps: |
          $env:PKGVER = Select-String -Path .\DESCRIPTION -Pattern '^Version: ' | % {$_.line -replace "^Version: "}
          $env:PKGNAME = Select-String -Path .\DESCRIPTION -Pattern '^Package: ' | % {$_.line -replace "^Package: "}
          $SRC_PKG_FILE = "${env:PKGNAME}_$env:PKGVER"
          Write-Host "File is $SRC_PKG_FILE"
          $env:BIN_PKG_FILE = Get-ChildItem -Path . | Where-Object { $_.Extension -eq ".zip" }
          Write-Host "Resulting binary: $env:BIN_PKG_FILE"

deploy:
  tag: '$(PKGNAME)-v$(PKGVER)'
  release: '$(PKGNAME)-v$(PKGVER)'
  description: ''
  provider: GitHub
  auth_token:
    secure: DH+SAcOLfr0THJKFwqo8rZocwIRYLfZuDE4RPV2mjYvNr5cYa4vo3dlVehRfX6Ce
  artifact: $(BIN_PKG_FILE)
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

environment:
  USE_RTOOLS: true
  NOT_CRAN: true
  R_VERSION: 3.6.3

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
